plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'org.sanchez.api'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation libs.junit.jupiter

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

test {
    useJUnitPlatform()
}